# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-23 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=16)),
                ('mob', models.CharField(max_length=64, verbose_name='Mobile No')),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('email', models.CharField(max_length=64)),
                ('clinic', models.CharField(max_length=64, verbose_name='Clinic')),
                ('bite', models.CharField(max_length=64, verbose_name='Location of Bite')),
                ('reg_date', models.DateField()),
                ('remarks', models.CharField(max_length=64, verbose_name='Special Remarks')),
                ('key', models.CharField(max_length=32)),
                ('day1_status', models.CharField(max_length=32)),
                ('day1', models.DateField(blank=True)),
                ('real_day1', models.DateField(blank=True)),
                ('msg_day1', models.CharField(blank='False', max_length=64)),
                ('day2_status', models.CharField(max_length=32)),
                ('day2', models.DateField(blank=True)),
                ('real_day2', models.DateField(blank=True)),
                ('msg_day2', models.CharField(blank='False', max_length=64)),
                ('day3_status', models.CharField(max_length=32)),
                ('day3', models.DateField(blank=True)),
                ('real_day3', models.DateField(blank=True)),
                ('msg_day3', models.CharField(blank='False', max_length=64)),
                ('day4_status', models.CharField(max_length=32)),
                ('day4', models.DateField(blank=True)),
                ('real_day4', models.DateField(blank=True)),
                ('msg_day4', models.CharField(blank='False', max_length=64)),
                ('status', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SMSModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0)),
            ],
        ),
    ]
