# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-23 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170123_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmodel',
            name='name',
            field=models.IntegerField(default=0),
        ),
    ]
