# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-23 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_smsmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmodel',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
